### ISSUE TITLE
Logging indicates only one issue was created where multiple were

### ISSUE THREAD

**Issue by jczimskey** [benbalter/bulk-issue-creator#19]
### Describe the bug

When looking at the [output log](https://github.com/jczimskey/bulk-issue-creator/actions/runs/8144492893/job/22258695389) from my most recent workflow run, it indicates only one issue was created. I confirmed in my other target repos from my data.csv, and those issues were indeed created.

### Steps to reproduce the behavior

1. Look at the [workflow output ](https://github.com/jczimskey/bulk-issue-creator/actions/runs/8144492893/job/22258695389)from this job run. This indicates only one issue in /torched-marshmallows was created.
2. In my data.csv file, /issues-graph was another target repo, along with several others.
3. Observe [this issue](https://github.com/github/issues-graph/issues/2498) was indeed created, but it does not show in the log from that workflow run.

### Expected behavior

The output logging should note all repos that issues were created or updated in.

**Comment by benbalter** [comment]
Wow. I haven't made a mistake that obvious in a while! 😆 Fixed via https://github.com/benbalter/bulk-issue-creator/pull/20 (moved the logging logic into the `for` loop, where it belongs), and pushed a new `v2` tag.

**Comment by benbalter** [comment]
[Confirmed](https://github.com/benbalter/bulk-issue-creator/actions/runs/8145167728/job/22260807736) that this is fixed.


![Image](https://github.com/benbalter/bulk-issue-creator/assets/282759/a7024a87-b83c-4979-b0ce-faf46885aa3a)
